pub mod password;
pub mod jwt;
pub mod service;
pub mod oidc;
pub mod mfa;
pub mod account_lockout;
pub mod email;
pub mod sms;
pub mod verification;
pub mod password_reset;
pub mod invitation;
pub mod audit_service;
pub mod organization_service;
pub mod connection_service;
pub mod application_service;
pub mod action_service;
pub mod action_executor;
pub mod billing_service;
pub mod oauth2_service;
pub mod error;

pub use password::PasswordHasher;
pub use jwt::{JwtService, Claims};
pub use service::{AuthService, AuthResponse, LoginRequest, HierarchicalLoginRequest, RefreshTokenRequest, RegisterRequest};
pub use oidc::{OidcService, OidcProviderTemplate, get_provider_template, list_provider_templates, apply_template_values};
pub use mfa::{generate_backup_codes, generate_qr_code, generate_secret, generate_totp_uri, verify_totp, hash_backup_code, verify_backup_code};
pub use email::{EmailService, EmailProvider, EmailMessage};
pub use sms::{SmsService, SmsProvider, SmsMessage};
pub use verification::VerificationService;
pub use password_reset::PasswordResetService;
pub use invitation::{InvitationService, Invitation};
pub use audit_service::AuditService;
pub use organization_service::{OrganizationService, OrganizationWithStats};
pub use connection_service::{ConnectionService, AuthMethod};
pub use application_service::ApplicationService;
pub use action_service::ActionService;
pub use action_executor::ActionExecutor;
pub use billing_service::BillingService;
pub use oauth2_service::OAuth2Service;
pub use error::{AuthError, Result};
